const testData = {
  '3IfMm': {
    solved: [
      'https://lichess.org/training/M3HN9',
      'https://lichess.org/training/ieXFm',
      'https://lichess.org/training/uUjXI',
      'https://lichess.org/training/xqmrg',
      'https://lichess.org/training/ObhSh',
      'https://lichess.org/training/ZVaBJ',
      'https://lichess.org/training/2brl9',
      'https://lichess.org/training/rd5ZD',
      'https://lichess.org/training/zUj79',
      'https://lichess.org/training/zFcfx',
      'https://lichess.org/training/XtB6q',
      'https://lichess.org/training/5OZOW',
      'https://lichess.org/training/zFOwG',
      'https://lichess.org/training/tgOgh',
    ],
    timestamp: 1764004111825,
    unsolved: [
      'https://lichess.org/training/0fau2',
      'https://lichess.org/training/F0OU4',
      'https://lichess.org/training/cGkDJ',
      'https://lichess.org/training/RLVQV',
      'https://lichess.org/training/1W0lk',
    ],
    reviewed: ['https://lichess.org/training/RLVQV', 'https://lichess.org/training/1W0lk'],
  },
  fJp7p: {
    solved: [
      'https://lichess.org/training/Ng8NW',
      'https://lichess.org/training/tfK4q',
      'https://lichess.org/training/AmCMr',
      'https://lichess.org/training/dleAw',
      'https://lichess.org/training/BWG1I',
      'https://lichess.org/training/UUtg6',
      'https://lichess.org/training/TRECW',
      'https://lichess.org/training/dU1WR',
      'https://lichess.org/training/smxYb',
      'https://lichess.org/training/YQbWR',
      'https://lichess.org/training/k1DDl',
      'https://lichess.org/training/hFFwm',
      'https://lichess.org/training/Zu0pO',
      'https://lichess.org/training/iDsNG',
      'https://lichess.org/training/sTtQs',
      'https://lichess.org/training/eaYRe',
    ],
    timestamp: 1764001949271,
    unsolved: ['https://lichess.org/training/5f2MM', 'https://lichess.org/training/5WIkg'],
  },
};
