const testData = {
  '3DO06': {
    reviewed: [],
    solved: [],
    timestamp: 1764080009647,
    unsolved: ['https://lichess.org/training/7EYpr'],
  },
  '47y0O': {
    reviewed: [],
    solved: [
      'https://lichess.org/training/6172L',
      'https://lichess.org/training/0lZ57',
      'https://lichess.org/training/aLVnR',
      'https://lichess.org/training/OCkKE',
      'https://lichess.org/training/8TPx0',
      'https://lichess.org/training/iPYZi',
      'https://lichess.org/training/tEcN7',
      'https://lichess.org/training/K6PBR',
      'https://lichess.org/training/6UCZv',
      'https://lichess.org/training/3zVEa',
      'https://lichess.org/training/0XTs8',
      'https://lichess.org/training/VaoCU',
      'https://lichess.org/training/y9j4Q',
      'https://lichess.org/training/3weM4',
      'https://lichess.org/training/w1lHD',
    ],
    timestamp: 1764080239471,
    unsolved: ['https://lichess.org/training/EvgfC', 'https://lichess.org/training/asbLG', 'https://lichess.org/training/nIc07'],
  },
  '5fDS6': {
    reviewed: ['https://lichess.org/training/bjtvB', 'https://lichess.org/training/CSeFE', 'https://lichess.org/training/WBYYa'],
    solved: [
      'https://lichess.org/training/oY7ZK',
      'https://lichess.org/training/658Bz',
      'https://lichess.org/training/LQv7c',
      'https://lichess.org/training/FoVLR',
      'https://lichess.org/training/FPpS7',
      'https://lichess.org/training/qDIo9',
      'https://lichess.org/training/Qjcdi',
      'https://lichess.org/training/0oRbO',
      'https://lichess.org/training/iHDHZ',
      'https://lichess.org/training/aOSFQ',
      'https://lichess.org/training/tEH9J',
      'https://lichess.org/training/GDm05',
      'https://lichess.org/training/wZNPA',
      'https://lichess.org/training/K9ItF',
      'https://lichess.org/training/GQu4v',
      'https://lichess.org/training/0ecsr',
      'https://lichess.org/training/CA4Li',
      'https://lichess.org/training/60UR0',
      'https://lichess.org/training/1q1Cr',
      'https://lichess.org/training/yoBhW',
    ],
    timestamp: 1764064195595,
    unsolved: [],
  },
  '7pRHx': {
    reviewed: [
      'https://lichess.org/training/ai8zZ',
      'https://lichess.org/training/1yt2N',
      'https://lichess.org/training/pUEEN',
      'https://lichess.org/training/2YLxc',
      'https://lichess.org/training/pmbO9',
      'https://lichess.org/training/xI4BL',
      'https://lichess.org/training/3Y8qO',
    ],
    solved: [
      'https://lichess.org/training/pPuHc',
      'https://lichess.org/training/LRlDY',
      'https://lichess.org/training/BhKha',
      'https://lichess.org/training/HHLsE',
      'https://lichess.org/training/uYoKm',
      'https://lichess.org/training/7GcUd',
      'https://lichess.org/training/SxQFg',
      'https://lichess.org/training/Ln6ti',
      'https://lichess.org/training/ACLNK',
      'https://lichess.org/training/r6i2S',
      'https://lichess.org/training/m3UJm',
      'https://lichess.org/training/8lhUe',
      'https://lichess.org/training/7WjYx',
      'https://lichess.org/training/T7ULg',
    ],
    timestamp: 1764019650572,
    unsolved: [],
  },
  D1msG: {
    reviewed: ['https://lichess.org/training/d40zi', 'https://lichess.org/training/TbWRN', 'https://lichess.org/training/KbR9C'],
    solved: [
      'https://lichess.org/training/vKVqL',
      'https://lichess.org/training/xERIT',
      'https://lichess.org/training/iqYvm',
      'https://lichess.org/training/0uqYY',
      'https://lichess.org/training/4GCkb',
      'https://lichess.org/training/407Fe',
      'https://lichess.org/training/Y5sxU',
      'https://lichess.org/training/quLfH',
      'https://lichess.org/training/JrMwQ',
      'https://lichess.org/training/MFZw9',
      'https://lichess.org/training/nHCmr',
      'https://lichess.org/training/gwXrU',
      'https://lichess.org/training/TZEQ9',
      'https://lichess.org/training/rAaNq',
      'https://lichess.org/training/NYZ9r',
    ],
    timestamp: 1764012796939,
    unsolved: [],
  },
  E87RN: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/h35aN',
      'https://lichess.org/training/SCnVI',
      'https://lichess.org/training/ELSGl',
      'https://lichess.org/training/Pf11K',
      'https://lichess.org/training/ajlJc',
      'https://lichess.org/training/6OJ4B',
      'https://lichess.org/training/8xyA2',
      'https://lichess.org/training/s5I1n',
      'https://lichess.org/training/6QjWb',
      'https://lichess.org/training/dMlgl',
      'https://lichess.org/training/2THru',
      'https://lichess.org/training/wUNHM',
      'https://lichess.org/training/tjWhO',
      'https://lichess.org/training/PeLSq',
    ],
    timestamp: 1764081368292,
    unsolved: ['https://lichess.org/training/v1o0F', 'https://lichess.org/training/EXuuZ'],
  },
  Ni6G1: {
    reviewed: [
      'https://lichess.org/training/XFRZJ',
      'https://lichess.org/training/zdphz',
      'https://lichess.org/training/02viR',
      'https://lichess.org/training/ZEvVq',
      'https://lichess.org/training/Lpkc4',
    ],
    solved: [
      'https://lichess.org/training/rdgVI',
      'https://lichess.org/training/4a5JS',
      'https://lichess.org/training/dZZTR',
      'https://lichess.org/training/c1Q4t',
      'https://lichess.org/training/407Fe',
      'https://lichess.org/training/CEzy9',
      'https://lichess.org/training/4RBI2',
      'https://lichess.org/training/v5BJD',
      'https://lichess.org/training/5lSD0',
      'https://lichess.org/training/HJjDn',
      'https://lichess.org/training/GTLSh',
      'https://lichess.org/training/7cHb3',
      'https://lichess.org/training/Iaoqo',
      'https://lichess.org/training/iIAw6',
      'https://lichess.org/training/ljtUh',
      'https://lichess.org/training/BMcwO',
    ],
    timestamp: 1764014115332,
    unsolved: [],
  },
  OPI3p: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/K5ErX',
      'https://lichess.org/training/GwxBp',
      'https://lichess.org/training/73Azl',
      'https://lichess.org/training/lHjt8',
      'https://lichess.org/training/7Vfjy',
      'https://lichess.org/training/BDRtO',
      'https://lichess.org/training/Ftnbo',
      'https://lichess.org/training/bMRhN',
      'https://lichess.org/training/lj7Tm',
      'https://lichess.org/training/tiKuI',
      'https://lichess.org/training/avS6I',
      'https://lichess.org/training/M8IiC',
      'https://lichess.org/training/sW6Pv',
      'https://lichess.org/training/Hl2Vt',
    ],
    timestamp: 1764082119609,
    unsolved: [
      'https://lichess.org/training/CoSH4',
      'https://lichess.org/training/uU04d',
      'https://lichess.org/training/aowlx',
      'https://lichess.org/training/tPM1r',
      'https://lichess.org/training/FT6Ao',
      'https://lichess.org/training/xB6iK',
      'https://lichess.org/training/RD7eL',
    ],
  },
  OxjI9: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/AwGc6',
      'https://lichess.org/training/gXU0K',
      'https://lichess.org/training/p75aO',
      'https://lichess.org/training/ljmHY',
      'https://lichess.org/training/spn3P',
      'https://lichess.org/training/Jvfln',
      'https://lichess.org/training/nGXPt',
      'https://lichess.org/training/jkj1s',
      'https://lichess.org/training/XLmHs',
      'https://lichess.org/training/I4mtn',
      'https://lichess.org/training/WiUF9',
      'https://lichess.org/training/OKwHL',
      'https://lichess.org/training/BHJQg',
      'https://lichess.org/training/TfxQn',
      'https://lichess.org/training/uAKsr',
      'https://lichess.org/training/jr2DX',
    ],
    timestamp: 1764080481684,
    unsolved: [
      'https://lichess.org/training/MmeYE',
      'https://lichess.org/training/F3zzb',
      'https://lichess.org/training/KPAhV',
      'https://lichess.org/training/10qIR',
      'https://lichess.org/training/VvXnP',
      'https://lichess.org/training/xUkGA',
      'https://lichess.org/training/ENC3Q',
    ],
  },
  SSivT: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/x17kD',
      'https://lichess.org/training/OwqIE',
      'https://lichess.org/training/BrR5U',
      'https://lichess.org/training/NVt3G',
      'https://lichess.org/training/pRL3I',
      'https://lichess.org/training/q77Jq',
      'https://lichess.org/training/y4KEz',
      'https://lichess.org/training/7m2tp',
      'https://lichess.org/training/JddUM',
      'https://lichess.org/training/IkEmB',
      'https://lichess.org/training/Y5Oh1',
      'https://lichess.org/training/ZHMQH',
      'https://lichess.org/training/mfu0F',
      'https://lichess.org/training/nPCNS',
      'https://lichess.org/training/z8ZZR',
      'https://lichess.org/training/rYiq3',
    ],
    timestamp: 1764082499534,
    unsolved: [
      'https://lichess.org/training/hnEGS',
      'https://lichess.org/training/k9JTE',
      'https://lichess.org/training/gVgPU',
      'https://lichess.org/training/lQ8L1',
      'https://lichess.org/training/L1VzG',
    ],
  },
  T9USX: {
    reviewed: [],
    solved: [],
    timestamp: 1764081654160,
    unsolved: ['https://lichess.org/training/3MmaF'],
  },
  ZF3Lj: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/PvkVJ',
      'https://lichess.org/training/WLHz2',
      'https://lichess.org/training/6m9bc',
      'https://lichess.org/training/xvuvH',
      'https://lichess.org/training/HBF51',
      'https://lichess.org/training/TeGsn',
      'https://lichess.org/training/dQi2l',
      'https://lichess.org/training/qhDge',
      'https://lichess.org/training/eCatB',
      'https://lichess.org/training/kNxNu',
      'https://lichess.org/training/ZeGBV',
      'https://lichess.org/training/OgwBr',
      'https://lichess.org/training/dv7CN',
      'https://lichess.org/training/2PQPN',
      'https://lichess.org/training/tIzbA',
    ],
    timestamp: 1764082346932,
    unsolved: ['https://lichess.org/training/Werdb', 'https://lichess.org/training/Sf1u1', 'https://lichess.org/training/QAq3p', 'https://lichess.org/training/YZgrw'],
  },
  afX3w: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/Jgi4I',
      'https://lichess.org/training/9Akqg',
      'https://lichess.org/training/k2uDY',
      'https://lichess.org/training/NujTA',
      'https://lichess.org/training/AzrFP',
      'https://lichess.org/training/ZqwFO',
      'https://lichess.org/training/xrCDz',
      'https://lichess.org/training/yXDVK',
      'https://lichess.org/training/mFYI6',
      'https://lichess.org/training/msNQa',
      'https://lichess.org/training/pSFmz',
      'https://lichess.org/training/OtI9e',
      'https://lichess.org/training/xii34',
      'https://lichess.org/training/ofjP4',
      'https://lichess.org/training/EJmtW',
    ],
    timestamp: 1764081869788,
    unsolved: [
      'https://lichess.org/training/whMnl',
      'https://lichess.org/training/vWgVj',
      'https://lichess.org/training/AzOzl',
      'https://lichess.org/training/LZ1K3',
      'https://lichess.org/training/yyddv',
      'https://lichess.org/training/6IcUs',
      'https://lichess.org/training/1JJgZ',
    ],
  },
  j6PG6: {
    reviewed: [
      'https://lichess.org/training/k1wl7',
      'https://lichess.org/training/ofH8s',
      'https://lichess.org/training/ptxoC',
      'https://lichess.org/training/Vk7rY',
      'https://lichess.org/training/MzgJ1',
    ],
    solved: [
      'https://lichess.org/training/3W1DC',
      'https://lichess.org/training/794Bq',
      'https://lichess.org/training/4kmh7',
      'https://lichess.org/training/4xOkl',
      'https://lichess.org/training/KdDcB',
      'https://lichess.org/training/4QXi2',
      'https://lichess.org/training/iVe9i',
      'https://lichess.org/training/4GY7l',
      'https://lichess.org/training/YyG37',
      'https://lichess.org/training/n2wIh',
      'https://lichess.org/training/Cg7sI',
      'https://lichess.org/training/3bKcw',
    ],
    timestamp: 1764064075479,
    unsolved: ['https://lichess.org/training/jPZvx', 'https://lichess.org/training/kXuAl'],
  },
  lvvnj: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/KZARY',
      'https://lichess.org/training/GOcBw',
      'https://lichess.org/training/4Mg04',
      'https://lichess.org/training/GGwqx',
      'https://lichess.org/training/lNLYo',
      'https://lichess.org/training/eD4bg',
      'https://lichess.org/training/KJOZ8',
      'https://lichess.org/training/40FoQ',
      'https://lichess.org/training/femFc',
      'https://lichess.org/training/34TkD',
    ],
    timestamp: 1764080360338,
    unsolved: [
      'https://lichess.org/training/nrMxW',
      'https://lichess.org/training/Ti8HI',
      'https://lichess.org/training/dkEKn',
      'https://lichess.org/training/Ms6EX',
      'https://lichess.org/training/612u2',
      'https://lichess.org/training/H9FFz',
      'https://lichess.org/training/XYr2w',
      'https://lichess.org/training/m55eW',
      'https://lichess.org/training/alspf',
      'https://lichess.org/training/XkCfx',
      'https://lichess.org/training/T6QjR',
      'https://lichess.org/training/6jGGJ',
    ],
  },
  mDif8: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/xaW50',
      'https://lichess.org/training/0sHfV',
      'https://lichess.org/training/ONtXb',
      'https://lichess.org/training/bswtk',
      'https://lichess.org/training/XZ2yl',
      'https://lichess.org/training/XAnH8',
      'https://lichess.org/training/fKmRD',
      'https://lichess.org/training/HrnI8',
      'https://lichess.org/training/AxwJA',
      'https://lichess.org/training/4Qc8C',
      'https://lichess.org/training/p8xuj',
      'https://lichess.org/training/8HLmF',
      'https://lichess.org/training/Uo55C',
    ],
    timestamp: 1764080120428,
    unsolved: [
      'https://lichess.org/training/oQkEd',
      'https://lichess.org/training/6Llgm',
      'https://lichess.org/training/dnyv2',
      'https://lichess.org/training/7EovV',
      'https://lichess.org/training/Hko5m',
      'https://lichess.org/training/9Lhzf',
      'https://lichess.org/training/5M7Yg',
      'https://lichess.org/training/NRUes',
      'https://lichess.org/training/njQud',
    ],
  },
  mwcnM: {
    reviewed: ['https://lichess.org/training/tSFA2', 'https://lichess.org/training/eFOXt', 'https://lichess.org/training/cfQW9'],
    solved: [
      'https://lichess.org/training/CRa83',
      'https://lichess.org/training/V9VsP',
      'https://lichess.org/training/u0zzB',
      'https://lichess.org/training/CfED8',
      'https://lichess.org/training/KsZHS',
      'https://lichess.org/training/jbcUh',
      'https://lichess.org/training/ACLNK',
      'https://lichess.org/training/7Ps2q',
      'https://lichess.org/training/DeHN8',
      'https://lichess.org/training/zEvxw',
      'https://lichess.org/training/5EgRu',
    ],
    timestamp: 1764012557293,
    unsolved: [
      'https://lichess.org/training/dd3ph',
      'https://lichess.org/training/3dYvS',
      'https://lichess.org/training/hJuIM',
      'https://lichess.org/training/qLsfN',
      'https://lichess.org/training/VIKgB',
      'https://lichess.org/training/a7fEX',
    ],
  },
  xsZfO: {
    reviewed: [],
    solved: [
      'https://lichess.org/training/gimjE',
      'https://lichess.org/training/8W3i6',
      'https://lichess.org/training/v5kcA',
      'https://lichess.org/training/tbWsd',
      'https://lichess.org/training/6yHeE',
      'https://lichess.org/training/baFbw',
      'https://lichess.org/training/hWcza',
      'https://lichess.org/training/XuPnk',
      'https://lichess.org/training/zZ7sc',
      'https://lichess.org/training/ptRK0',
      'https://lichess.org/training/XuAFq',
      'https://lichess.org/training/oesp5',
    ],
    timestamp: 1764081032117,
    unsolved: [
      'https://lichess.org/training/1xCye',
      'https://lichess.org/training/1Lmt8',
      'https://lichess.org/training/BPjdn',
      'https://lichess.org/training/aB9T1',
      'https://lichess.org/training/XhTuD',
      'https://lichess.org/training/3fwhE',
      'https://lichess.org/training/StXAZ',
      'https://lichess.org/training/i6dkN',
      'https://lichess.org/training/nIc07',
      'https://lichess.org/training/qWydm',
    ],
  },
  zRz4R: {
    reviewed: ['https://lichess.org/training/1pqOD', 'https://lichess.org/training/9Ythr', 'https://lichess.org/training/7XHkL'],
    solved: [
      'https://lichess.org/training/Bvukd',
      'https://lichess.org/training/YZQbk',
      'https://lichess.org/training/B8vHT',
      'https://lichess.org/training/mNhLq',
      'https://lichess.org/training/2xFpS',
      'https://lichess.org/training/JvWM6',
      'https://lichess.org/training/F6XLw',
      'https://lichess.org/training/52lU3',
      'https://lichess.org/training/TqQhB',
      'https://lichess.org/training/LQfp7',
      'https://lichess.org/training/PXWB3',
      'https://lichess.org/training/hnOdE',
      'https://lichess.org/training/2GOk2',
      'https://lichess.org/training/yiHhU',
      'https://lichess.org/training/qriR5',
    ],
    timestamp: 1764021986355,
    unsolved: ['https://lichess.org/training/mscXs', 'https://lichess.org/training/HA6CQ'],
  },
};
